// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkrnbgtvceeathfwhlkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhrcm5iZ3R2Y2VlYXRoZndobGtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNDQ0MTYsImV4cCI6MjA3MjcyMDQxNn0.XXbradGUVOZnIe7_lMJw3PD3Npk80vJxVrw9uihFtQE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});