// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icjqyoujbxffmungelbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljanF5b3VqYnhmZm11bmdlbGJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNTY0ODAsImV4cCI6MjA3MjczMjQ4MH0.2r3tWjukqKb1z3UjGXs0ndlSB6PEm95rEbJcDKgTaBc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});